# meta-info

base: "cls"

tag: "w5"

# data info

batch_size: 16

image_size: 128

n_channels: 3

n_classes: 3

shuffle_buffer: 1000

sample:

    size: 100
    
    balanced: True
    
class_enum:

    major: 0
    
    minor: 1
    
    two-track: 2

# train info

learning_rate: 0.001

n_epochs: 5

tensorboard_freq: 50

balance_classes: True